### ISSUE TITLE
Month, not day?

### ISSUE THREAD

**Issue by zshoorbajee** [learn-co-curriculum/dsc-introduction-to-time-series#1]
## Link to Canvas

https://learning.flatironschool.com/courses/4959/assignments/175729?module_item_id=386180

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```
Rotate (transpose) the nyse_annual DataFrame as a new matrix so that each row represents one year and each column one **day**.
```

### Concern

Based on the code that follows, I think this should be **month**, not day.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [x] IllumiDesk

**Comment by christine-egan42** [comment]
I am not seeing this example in this repo. Will check the other time series reps to locate and correct the issue.
